google_api:
  production:
   client_id: '4225099662.apps.googleusercontent.com'
   client_secret: 'NlEMrLKkOkaPo1Y8UrwDeE5q'
   email: '4225099662@developer.gserviceaccount.com'
   scope:
    - 'https://www.googleapis.com/auth/userinfo.profile'
    - 'https://www.googleapis.com/auth/userinfo.email'
    - 'https://picasaweb.google.com/data/'
   redirect_uri: '/oauth2callback'
   registered_redirect_uri: 'http://intense-hamlet-3672.herokuapp.com/oauth2callback'
  dev:
   client_id: '4225099662-9lf90nl1q64abnqg4ar0v4vmqll3avgn.apps.googleusercontent.com'
   client_secret: 'GRzkp2SkeHmtGsQ4Grtttt15'
   email: '4225099662-9lf90nl1q64abnqg4ar0v4vmqll3avgn@developer.gserviceaccount.com'
   scope:
    - 'https://www.googleapis.com/auth/userinfo.profile'
    - 'https://www.googleapis.com/auth/userinfo.email'
    - 'https://picasaweb.google.com/data/'
   redirect_uri: '/oauth2callback'
   registered_redirect_uri: http://localhost:9393/oauth2callback
